deploy_composer:
  only:
    - tags
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install curl
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${COMPOSER_DEPLOY}@gitlab.mgmt.168tech.vip/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
